name: DispenserRefill
main: de.akkarin.DispenserRefill.DispenserRefill
version: 1.0.0a3
author: Akkarin
website: http://www.akkarin.de
description: This plugin allows administrators to make dispensers infinite. This means that they will never run out of ammo/content.
depend: [ WorldEdit ]
commands:
    autorefill:
        description: Enables auto-refilling on the dispenser you're facing.
        permission: dispenserRefill.set
        usage: /autorefill [disable]
        
permissions:
    dispenserRefill.set:
        description: Allows players to enable auto-refilling of the faced dispenser.
        default: op