name: DispenserRefill
description: Allows you to create never out of inventory running dispensers.
main: de.akkarin.DispenserRefill.DispenserRefillPlugin
version: "${project.version}"
depend: [WorldEdit]